"""Generate additive Phase 2 operation contracts; never alter Phase 1 sources."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
BASE='https://contracts.ecos.invalid/v1/'
def obj(p): return {'type':'object','properties':p,'required':list(p),'additionalProperties':False}
def text(n=200): return {'type':'string','minLength':1,'maxLength':n}
def integer(lo=0,hi=2147483647): return {'type':'integer','minimum':lo,'maximum':hi}
def ref(n): return {'$ref':BASE+n+'.schema.json'}
UUID={'type':'string','format':'uuid'}
TIME={'type':'string','format':'date-time'}
HASH={'type':'string','pattern':'^[a-f0-9]{64}$'}
FENCE=ref('claim_fence')
def main():
    claim=json.loads((ROOT/'contracts/operations/work.claim-request.schema.json').read_text())['properties']['arguments']
    fence=json.loads((ROOT/'contracts/operations/work.renew-request.schema.json').read_text())['properties']['arguments']['properties']['fence']
    specs={
      'executor.register':obj({'host':text(),'runtime':text(),'software_version':text(),'evidence_hash':HASH}),
      'executor.heartbeat':obj({'observed_at':TIME,'evidence_hash':HASH,'reported_running':integer(),'load_basis_points':integer(0,10000)}),
      'executor.stop':obj({'reason':text()}),
      'work.next':claim,
      'work.package':obj({'fence':fence}),
      'work.fail':obj({'fence':fence,'reason':{'type':'string','pattern':'^[a-z][a-z0-9_.-]{0,127}$'},'retryable':{'type':'boolean'}}),
      'work.defer':obj({'fence':fence,'reason':{'type':'string','pattern':'^[a-z][a-z0-9_.-]{0,127}$'},'until':TIME}),
      'work.release':obj({'fence':fence,'reason':{'type':'string','pattern':'^[a-z][a-z0-9_.-]{0,127}$'}}),
      'work.dead_letter':obj({'fence':fence,'reason':{'type':'string','pattern':'^[a-z][a-z0-9_.-]{0,127}$'}}),
      'semantic.proposal.submit':obj({'fence':fence,'proposal':ref('semantic_proposal')}),
      'recovery.sweep':obj({'limit':integer(1,100)}),
      'resource.observe':obj({'provider':text(80),'metric':text(80),'observed_at':TIME,'value':{'anyOf':[integer(),{'type':'null'}]},'evidence_hash':HASH}),
    }
    schemas={}
    for op,args in specs.items():
        name=op+'-request';schemas[name]={'$schema':'https://json-schema.org/draft/2020-12/schema','$id':BASE+name+'.schema.json','title':name,**obj({'schema_version':{'const':'1.0.0'},'context':ref('request_context'),'arguments':args})}
    schemas['phase2_result']={'$schema':'https://json-schema.org/draft/2020-12/schema','$id':BASE+'phase2_result.schema.json','title':'phase2_result',**obj({'schema_version':{'const':'1.0.0'},'correlation_id':UUID,'status':text(80),'data':{'type':'object'}})}
    ops=[{'name':op,'request_schema':BASE+op+'-request.schema.json','response_schema':BASE+'phase2_result.schema.json','required_role':'operations_api' if op in ('recovery.sweep','resource.observe','work.dead_letter') else 'executor','semantic_proposable':False,'idempotency_scope':'principal_id + operation + idempotency_key','atomicity':'single transaction'} for op in specs]
    folder=ROOT/'contracts/phase2';folder.mkdir(exist_ok=True)
    for name,schema in schemas.items(): (folder/(name+'.schema.json')).write_text(json.dumps(schema,indent=2)+'\n',encoding='utf-8',newline='\n')
    (folder/'operations.json').write_text(json.dumps({'schema_version':'1.0.0','operations':ops},indent=2)+'\n',encoding='utf-8',newline='\n')
    def literal(x): return "'"+json.dumps(x,separators=(',',':')).replace("'","''")+"'::jsonb"
    sql=['-- Additive Phase 2 contracts. Generated by scripts/build_phase2.py.','set local role ecos_owner;']
    for s in schemas.values():sql.append("insert into ecos_meta.contract_schema values('"+s['$id']+"',"+literal(s)+");")
    for o in ops:sql.append("insert into ecos_meta.operation_contract values('"+o['name']+"',"+literal(o)+");")
    sql.append('reset role;')
    (ROOT/'db/migrations/000019_control_plane_contracts.sql').write_text('\n'.join(sql)+'\n',encoding='utf-8',newline='\n')
    print('Generated additive Phase 2 contracts')
if __name__=='__main__':main()
