from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT/'scripts'))
import build_contracts as c
c.build()
schemas = {v['$id']:v for k,v in c.OUTPUTS.items() if k.endswith('.schema.json')}
def literal(x):
    return "'"+str(x).replace("'", "''")+"'"
def js(x):
    return literal(json.dumps(x,ensure_ascii=False,separators=(',',':')))+'::jsonb'
def write(name,text):
    target=ROOT/name
    if '--check' not in sys.argv:
        raise SystemExit('Historical migration generator is check-only. Add a new forward migration for changes.')
    if target.read_text(encoding='utf-8') != text:
        raise SystemExit('Historical migration recipe differs; never overwrite applied SQL: '+name)
    print('Verified historical typed-foundation migration recipe')

def resolve(p):
    if '$ref' in p:
        url,_,frag=p['$ref'].partition('#')
        p=schemas[url]
        for k in frag.strip('/').split('/') if frag else []: p=p[k]
    return p
def sqltype(p):
    p=resolve(p)
    if 'anyOf' in p: return sqltype(p['anyOf'][0])
    if isinstance(p.get('const'), bool): return 'boolean'
    if p.get('format')=='uuid': return 'uuid'
    if p.get('format')=='date-time': return 'timestamptz'
    return {'integer':'bigint','boolean':'boolean','object':'jsonb','array':'jsonb'}.get(p.get('type'),'text')
entities={v['title']:v for v in schemas.values() if 'id' in v.get('properties',{})}
def ns(n): return 'ecos_migration' if n in ('raw_migration_batch','quarantine_item','legacy_identity') else 'ecos'
sql=['''-- Typed physical projection of the unchanged Phase 0 wire contracts.
-- Generated by scripts/build_phase1_schema.py; review SQL before application.
create schema if not exists ecos_meta;
revoke all on schema ecos_meta from public;
create table ecos_meta.database_identity (
 singleton boolean primary key default true check(singleton),
 architecture_version text not null check(architecture_version='2.x'),
 schema_version text not null check(schema_version='1.0.0'),
 environment text not null check(environment='development'),
 authority text not null check(authority='non_production'),
 provider_effects_enabled boolean not null check(not provider_effects_enabled));
insert into ecos_meta.database_identity values(true,'2.x','1.0.0','development','non_production',false);
create table ecos_meta.contract_schema (schema_id text primary key, document jsonb not null);
create table ecos_meta.operation_contract (name text primary key, document jsonb not null);
create table ecos_meta.transition_policy (name text primary key, edges jsonb not null);
create table ecos_meta.entity_contract (name text primary key, schema_id text not null references ecos_meta.contract_schema, immutable boolean not null);
''']
for id_,s in schemas.items(): sql.append(f'insert into ecos_meta.contract_schema values({literal(id_)},{js(s)});')
for o in c.OUTPUTS['contracts/operations/registry.json']['operations']: sql.append(f"insert into ecos_meta.operation_contract values({literal(o['name'])},{js(o)});")
for n,e in json.loads((ROOT/'config/lifecycle-transitions.json').read_text())['transitions'].items(): sql.append(f'insert into ecos_meta.transition_policy values({literal(n)},{js(e)});')
sql.append('''create table ecos.party(id uuid primary key default gen_random_uuid(), business_id text not null unique, name text not null, record_version bigint not null default 1 check(record_version>0));
create table ecos.project(id uuid primary key default gen_random_uuid(), business_id text not null unique, title text not null, record_version bigint not null default 1 check(record_version>0));
create table ecos.artifact(id uuid primary key default gen_random_uuid(), business_id text not null unique, provider text not null, provider_object_id text not null, uri text not null, content_hash text not null check(content_hash ~ '^[a-f0-9]{64}$'), record_version bigint not null default 1 check(record_version>0), unique(provider,provider_object_id));
create table ecos.fact(id uuid primary key default gen_random_uuid(), subject_id uuid not null, statement text not null, source_references jsonb not null, sensitivity text not null check(sensitivity in ('public','internal','confidential','restricted')), record_version bigint not null default 1 check(record_version>0), created_at timestamptz not null default clock_timestamp());
''')
for n,s in entities.items():
    cols=[]
    for k,p in s['properties'].items():
        if k=='fence' and n=='execution_run': continue
        nullable='anyOf' in p and any(x.get('type')=='null' for x in p['anyOf'])
        typ=sqltype(p)
        col=f'"{k}" {typ}'+('' if nullable else ' not null')
        if k=='id': col+=' default gen_random_uuid() primary key'
        elif k=='schema_version': col+=" default '1.0.0'"
        elif k=='created_at': col+=' default clock_timestamp()'
        elif k=='record_version': col+=' default 1'
        elif k in ('claim_version','attempt_count') and n=='work_occurrence': col+=' default 0'
        r=resolve(p)
        if 'const' in r: col+=' check("'+k+'" = '+(str(r['const']).lower() if isinstance(r['const'],bool) else literal(r['const']))+')'
        if 'enum' in r: col+=' check("'+k+'" in ('+','.join(literal(v) for v in r['enum'])+'))'
        if 'minimum' in r: col+=f' check("{k}" >= {r["minimum"]})'
        if 'maximum' in r: col+=f' check("{k}" <= {r["maximum"]})'
        if r.get('pattern')=='^[a-f0-9]{64}$': col+=f' check("{k}" ~ {literal(r["pattern"])})'
        cols.append(col)
    if n=='execution_run': cols.extend(['claim_id uuid not null unique','occurrence_id uuid not null','stage_definition_id uuid not null','claim_version bigint not null','fence_token uuid not null','executor_instance_id uuid not null'])
    sql.append(f'create table {ns(n)}.{n}(\n '+',\n '.join(cols)+'\n);')
    sql.append(f"insert into ecos_meta.entity_contract values({literal(n)},{literal(s['$id'])},{str('record_version' not in s['properties']).lower()});")

fks={
'task':{'project_id':'project'},'task_assignment':{'task_id':'task','party_id':'party'},'task_schedule':{'task_id':'task'},'task_dependency':{'task_id':'task','prerequisite_task_id':'task'},'approval_request':{'task_id':'task'},'approval_decision':{'approval_request_id':'approval_request','supersedes_decision_id':'approval_decision'},'task_evidence':{'task_id':'task'},
'work_definition':{'retry_policy_id':'retry_policy'},'work_stage_definition':{'work_definition_id':'work_definition'},'work_occurrence':{'work_definition_id':'work_definition','stage_definition_id':'work_stage_definition','task_id':'task'},'work_dependency':{'occurrence_id':'work_occurrence','prerequisite_occurrence_id':'work_occurrence'},'work_claim':{'occurrence_id':'work_occurrence','stage_definition_id':'work_stage_definition','executor_instance_id':'executor_instance'},'execution_run':{'claim_id':'work_claim'},'stage_result':{'occurrence_id':'work_occurrence','stage_definition_id':'work_stage_definition','execution_run_id':'execution_run'},'dead_letter_item':{'occurrence_id':'work_occurrence','last_run_id':'execution_run'},
'executor_instance':{'executor_id':'executor'},'executor_capability':{'executor_instance_id':'executor_instance'},'stage_capability_requirement':{'stage_definition_id':'work_stage_definition'},'heartbeat':{'executor_instance_id':'executor_instance'},'outbox_item':{'domain_event_id':'domain_event','provider_command_id':'provider_command'},'provider_command':{'approval_request_id':'approval_request'},'provider_attempt':{'provider_command_id':'provider_command'},'provider_result':{'provider_command_id':'provider_command','provider_attempt_id':'provider_attempt'},'communication':{'receipt_id':'provider_receipt','sender_party_id':'party'},'communication_processing':{'communication_id':'communication','occurrence_id':'work_occurrence','proposal_id':'semantic_proposal'},'delivery':{'notification_id':'notification','recipient_party_id':'party','approval_request_id':'approval_request','provider_command_id':'provider_command'},'delivery_attempt':{'delivery_id':'delivery','provider_attempt_id':'provider_attempt'},
'memory_record':{'scope_id':'memory_scope','active_head_version_id':'memory_version'},'memory_version':{'memory_record_id':'memory_record','scope_id':'memory_scope','supersedes_version_id':'memory_version','compaction_run_id':'memory_compaction_run'},'memory_reference':{'memory_version_id':'memory_version'},'memory_compaction_run':{'scope_id':'memory_scope','output_version_id':'memory_version'},'backup_record':{'restore_test_id':'restore_test'},'quarantine_item':{'batch_id':'raw_migration_batch','identity_resolution_id':'legacy_identity'},'legacy_identity':{'source_batch_id':'raw_migration_batch'}}
for n,fields in fks.items():
    for k,target in fields.items():
        sql.append(f'alter table {ns(n)}.{n} add foreign key ({k}) references {ns(target)}.{target}(id) deferrable initially immediate;')
        sql.append(f'create index on {ns(n)}.{n}({k});')
unique={'task':['business_id'],'work_definition':['name,definition_version'],'work_stage_definition':['work_definition_id,stage_key','id,work_definition_id'],'work_occurrence':['work_definition_id,stage_definition_id,occurrence_key','id,stage_definition_id'],'task_dependency':['task_id,prerequisite_task_id'],'work_dependency':['occurrence_id,prerequisite_occurrence_id'],'work_claim':['id,occurrence_id,stage_definition_id,claim_version,fence_token,executor_instance_id'],'execution_run':['id,occurrence_id,stage_definition_id'],'stage_result':['occurrence_id,stage_definition_id'],'executor_instance':['executor_id,boot_id'],'capability':['name,version'],'executor_capability':['executor_instance_id,capability_name'],'stage_capability_requirement':['stage_definition_id,capability_name'],'provider_command':['provider,account_scope,command_type,idempotency_key'],'provider_attempt':['provider_command_id,attempt_number','id,provider_command_id'],'provider_result':['provider_attempt_id,evidence_hash'],'provider_receipt':['provider,account_scope,dedupe_key'],'communication':['receipt_id'],'communication_processing':['communication_id,source_version'],'delivery':['notification_id,recipient_party_id,channel,policy_key'],'delivery_attempt':['delivery_id,provider_attempt_id'],'memory_scope':['scope_type,scope_id'],'memory_record':['business_id','scope_id,memory_kind','id,scope_id'],'memory_version':['memory_record_id,version_number','id,memory_record_id,scope_id'],'outbox_item':['destination,idempotency_key'],'quarantine_item':['batch_id,source_locator'],'legacy_identity':['source_system,source_family,source_batch_id,source_locator']}
for n,keys in unique.items():
    for key in keys: sql.append(f'alter table {ns(n)}.{n} add unique ({key});')
sql.append('''
alter table ecos.task add check((lifecycle_state='waiting')=(wait_reason<>'none'));
alter table ecos.task_dependency add check(task_id<>prerequisite_task_id);
alter table ecos.work_dependency add check(occurrence_id<>prerequisite_occurrence_id);
alter table ecos.task_assignment add check(effective_to is null or effective_to>effective_from);
alter table ecos.work_claim add check(expires_at>acquired_at);
alter table ecos.work_occurrence add foreign key(stage_definition_id,work_definition_id) references ecos.work_stage_definition(id,work_definition_id);
alter table ecos.work_claim add foreign key(occurrence_id,stage_definition_id) references ecos.work_occurrence(id,stage_definition_id);
alter table ecos.execution_run add foreign key(claim_id,occurrence_id,stage_definition_id,claim_version,fence_token,executor_instance_id) references ecos.work_claim(id,occurrence_id,stage_definition_id,claim_version,fence_token,executor_instance_id);
alter table ecos.stage_result add foreign key(execution_run_id,occurrence_id,stage_definition_id) references ecos.execution_run(id,occurrence_id,stage_definition_id);
alter table ecos.memory_record add foreign key(active_head_version_id,id,scope_id) references ecos.memory_version(id,memory_record_id,scope_id) deferrable initially deferred;
alter table ecos.memory_version add foreign key(memory_record_id,scope_id) references ecos.memory_record(id,scope_id);
alter table ecos.provider_result add foreign key(provider_attempt_id,provider_command_id) references ecos.provider_attempt(id,provider_command_id);
alter table ecos.executor_capability add foreign key(capability_name,capability_version) references ecos.capability(name,version);
create unique index work_claim_one_active on ecos.work_claim(occurrence_id,stage_definition_id) where state='active';
create index work_occurrence_ready on ecos.work_occurrence(due_at,created_at,id) where state in ('pending','ready','retry_wait','claimed','running');
create index outbox_pending on ecos.outbox_item(available_at,created_at,id) where state in ('pending','retry_wait','claimed');
create index heartbeat_latest on ecos.heartbeat(executor_instance_id,received_at desc);
create index heartbeat_expiry on ecos.heartbeat(valid_until);
create index memory_active_head on ecos.memory_record(scope_id,memory_kind) where active_head_version_id is not null;
create table ecos_meta.principal_binding(role_name name primary key,principal_id uuid not null,executor_instance_id uuid references ecos.executor_instance, enabled boolean not null default true);
create table ecos_meta.principal_operation(principal_id uuid not null,operation text not null references ecos_meta.operation_contract,primary key(principal_id,operation));
create table ecos_meta.object_grant(principal_id uuid not null,record_type text not null,record_id uuid not null,primary key(principal_id,record_type,record_id));
create table ecos_meta.operation_receipt(principal_id uuid not null,operation text not null,idempotency_key text not null,request_hash text not null,result jsonb not null,created_at timestamptz not null default clock_timestamp(),primary key(principal_id,operation,idempotency_key));
create table ecos_meta.operation_audit(id uuid primary key default gen_random_uuid(),operation text not null,principal_id uuid not null,correlation_id uuid not null,causation_id uuid,request_hash text not null,result_hash text not null,created_at timestamptz not null default clock_timestamp());
create table ecos_meta.control(singleton boolean primary key default true check(singleton),maintenance boolean not null default false,record_version bigint not null default 1);
insert into ecos_meta.control values(true,false,1);
create table ecos_meta.proposal_item_result(proposal_id uuid not null references ecos.semantic_proposal,item_id uuid not null,proposal_hash text not null,result jsonb not null,primary key(proposal_id,item_id));
create table ecos.work_priority(occurrence_id uuid primary key references ecos.work_occurrence, sla_deadline timestamptz,deadline timestamptz,business_impact bigint not null default 0 check(business_impact between 0 and 100),recurrence_period_seconds bigint check(recurrence_period_seconds>0));
create table ecos.work_approval(occurrence_id uuid primary key references ecos.work_occurrence,approval_request_id uuid not null references ecos.approval_request,expected_subject_hash text not null);
create table ecos.command_occurrence(provider_command_id uuid primary key references ecos.provider_command,occurrence_id uuid not null references ecos.work_occurrence);
create table ecos_meta.outbox_lease(item_id uuid primary key references ecos.outbox_item,token uuid not null,principal_id uuid not null);
create table ecos.integrity_finding(id uuid primary key default gen_random_uuid(),condition text not null,entity_id uuid not null,before_state jsonb not null,detected_at timestamptz not null default clock_timestamp(),correlation_id uuid not null);
create table ecos.repair_action(id uuid primary key default gen_random_uuid(),finding_id uuid not null unique references ecos.integrity_finding,before_state jsonb not null,after_state jsonb not null,procedure_name text not null,created_at timestamptz not null default clock_timestamp(),correlation_id uuid not null,result text not null check(result in ('repaired','not_applicable')));
create table ecos.emergency_intent(id uuid primary key default gen_random_uuid(),executor_instance_id uuid not null references ecos.executor_instance,heartbeat_id uuid references ecos.heartbeat,condition text not null,created_at timestamptz not null default clock_timestamp(),correlation_id uuid not null,unique(executor_instance_id,heartbeat_id,condition));
create table ecos.export_package(id uuid primary key,manifest jsonb not null,content_hash text not null,created_at timestamptz not null default clock_timestamp());
create table ecos_migration.raw_source_row(batch_id uuid not null references ecos_migration.raw_migration_batch,source_locator text not null,raw_value jsonb not null,raw_hash text not null,primary key(batch_id,source_locator));
create table ecos_meta.notification_policy(task_id uuid primary key references ecos.task,recipient_party_id uuid not null references ecos.party,channel text not null check(channel in ('sms','email')),destination_reference text not null,content_artifact_uri text not null,content_hash text not null,policy_key text not null);
''')
write('db/migrations/000002_typed_foundation.sql','\n'.join(sql)+'\n')
